carpool/carpool/carpool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logPage.urls')),
    path('rider/', include('rider.urls')),
    path('driver/', include('driver.urls'))
]

carpool/carpool/logPage/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views

app_name = 'logPage'

# urlpatterns = [
# 	path('' , views.index , name = "index"),
# 	url(r'^(?P<album_id>[0-9]+)/$' , views.detail , name = "detail"),
# 	url(r'^(?P<album_id>[0-9]+)/favorite/$' , views.favorite , name = "favorite")
# ]

# urlpatterns = [
# 	path('' , views.IndexView.as_view() , name = "index"),
# 	url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name = "detail"),
# 	url(r'^album/add/$', views.createAlbum.as_view() , name = "album-add")
# ]

urlpatterns = [
	path('', views.index, name="index"),
	path('register.html', views.register, name="register"),
	path('forgot-password.html', views.forget , name = "forget"),
	path('option/' , views.drive_or_ride , name = "option"),
	path('registerUser/' , views.addUser , name = "registerUser"),
	path('verifyUser/' , views.verifyUser , name = "authenticate"),
]

carpool/carpool/rider/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views

app_name = 'rider'

# urlpatterns = [
# 	path('' , views.index , name = "index"),
# 	url(r'^(?P<album_id>[0-9]+)/$' , views.detail , name = "detail"),
# 	url(r'^(?P<album_id>[0-9]+)/favorite/$' , views.favorite , name = "favorite")
# ]

# urlpatterns = [
# 	path('' , views.IndexView.as_view() , name = "index"),
# 	url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name = "detail"),
# 	url(r'^album/add/$', views.createAlbum.as_view() , name = "album-add")
# ]

urlpatterns = [
	path('' , views.index , name = "ride"),
	path('submit', views.rideInfo, name = "rideInfo"),
	path('processsing', views.statusUpdate, name = "statusUpdate"),
	path('success', views.rideSuccessful, name = "rideSuccessful"),
	path('riderQuestions', views.riderQuestions, name="riderQuestions"),
	path('riderAnswer', views.riderAnswer, name="riderAnswer")
	# path('rideRemove', views.endRide, name = "endRide"),
]

carpool/carpool/rider/models.py
from django.db import models
from django.db import transaction
# Create your models here.
class ride(models.Model):
	userId = models.CharField(max_length = 200 , primary_key=True)
	pickUp = models.CharField(max_length = 200)
	destination = models.CharField(max_length = 200)
	complete = models.BooleanField(default=False)
	status = models.BooleanField(default=False)
	cost = models.PositiveIntegerField(default = 0)
	driverId = models.CharField(max_length = 200 , default = None, null = True)
	expectedTime = models.CharField(max_length=200, default="inf")

	def __str__(self):
		return (self.userId + " ---- " + self.destination)

	@classmethod
	def acceptRide(self , riderId , driverId):
		print("acceptRide of ride model ########################")
		success = True
		with transaction.atomic():
			r = ride.objects.select_for_update().get(pk = riderId)
			if r.status == True or r.complete == True:
				success = False
			else:
				r.driverId = driverId
				r.status = True
				r.save()

		return success

carpool/carpool/rider/views.py
from django.shortcuts import render
from django.http import HttpResponse ,Http404
from django.template import loader
from django.shortcuts import render , get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView , UpdateView , DeleteView
from .models import ride
import numpy as np
import googlemaps 
import json
import sqlite3
from django.core import serializers
import time


from django.http import JsonResponse


# Create your views here.

def index(request):
	print(request.user.username)
	return render(request , "riderHome.html" , {'username' : request.user.username})
	# return HttpResponse("<h1>SUCCESS</h1>")

def rideInfo(request):
	if request.method == "POST":
		print("ride info---------------------------------------------------------------------------------------")
		print(request.POST['userId'])
		print(request.POST['pickup'])
		print(request.POST['destination'])
		print(request.POST['latVal'])
		print(request.POST['lngVal']) 
		print(type(request.POST))
		r = ride(
			userId = request.POST['userId'], 
			pickUp = request.POST['pickup'],
			destination = request.POST['destination']
		)
		r.save()
		context ={'paramDict' : {'userId' : request.POST['userId'],'pickup' : request.POST['pickup'] , 'latVal' : request.POST['latVal'] , 
					'lngVal' : request.POST['lngVal'] , 'destination' : request.POST['destination'] }}
		#model of ride created
	return render(request , "blank.html" , context)

def statusUpdate(request):
	print("here ----------------------------------")
	id = request.GET['id']
	update =request.GET['update']
	gmaps = googlemaps.Client(key='AIzaSyCG-rWicPLs2VaZF3WDK6yyl7tQqh-kUUc')
	rideDetils = get_object_or_404(ride, pk=id)

	my_dist_1 = gmaps.distance_matrix(rideDetils.pickUp , rideDetils.destination)['rows'][0]['elements'][0]["distance"]["value"]
	time.sleep(10)

	my_dist_1 = gmaps.distance_matrix(rideDetils.pickUp, rideDetils.destination)['rows'][0]['elements'][0]["distance"][
		"value"]

	my_dist_1 = my_dist_1/1000.0
	my_dist_1 = int(my_dist_1 *10)
	print("hello ----------------------------------",id)
	if rideDetils.status :
		if rideDetils.complete:
			return JsonResponse({'success':True,'driverId':rideDetils.driverId,'complete':True,'cost':my_dist_1, 'expectedTime':rideDetils.expectedTime})
		else:
			return JsonResponse({'success':True,'driverId':rideDetils.driverId,'complete':False,'cost':my_dist_1, 'expectedTime':rideDetils.expectedTime})
	return JsonResponse({'success':False,'driverId':"none",'complete':False,'cost':0, 'expectedTime':rideDetils.expectedTime})

## UNCOMMENT - if we redirect to new page after ride acceptance
def rideSuccessful(request):
	print("kkk ----------------------------------")
	if request.method == "POST":
		id = request.POST['userId']
		print("rider id", id)
		rideDetails = get_object_or_404(ride, pk=id)
	#return render(request, 'polls/results.html', {'rideDetails': rideDetails})
	return HttpResponse("<h1>SUCCESS </h1>")

# def endRide(request):
# 	print(request.GET['id'], "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^")
# 	ride.objects.filter(pk=request.GET['id']).delete()
# 	print("^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^6")
# 	return render(request , "drive_or_ride.html" , {'user': request.GET['id']})

def riderQuestions(request):
    print(request.user.username)
    return render(request, "riderSideQuestion.html", {'username': request.user.username})


def riderAnswer(request):
    if request.method == "POST":
        userid = request.user.username
        riderid = userid
        talkative = request.POST.get('talkative')
        timedriving = request.POST.get('timedriving')
        music = request.POST.get('music')
        male = request.POST.get('male')
        female = request.POST.get('female')
        student = request.POST.get('student')
        working = request.POST.get('working')
        con = sqlite3.connect("db.sqlite3")
        cur = con.cursor()
        values = (userid, riderid, talkative, timedriving, music, male, female, student, working)
        cur.execute("insert into rider_question values (?, ?, ?, ?, ?, ?, ?, ?, ?)", values)
        con.commit()
        return render(request, "riderHome.html", {'username': request.user.username})

carpool/carpool/rider/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SR Admin 2 - Login</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 130px;
      }
    </style>
</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.jpeg' %}" alt="Carpool" align = "center"/>
                 </span>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome!!</h1>
                  </div>
                  <form action="{% url 'logPage:authenticate' %}" name = "authenticate" method = "post" class= "user">
                    {% csrf_token %} # used to save from attack, information stolen
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name = "userId" id="userId" placeholder="Enter User Id">
                    </div>
                    <div class="form-group">
                      <input type="password" class="form-control form-control-user" name = "passWd" id="passWd" placeholder=" Enter Password">
                    </div>
                    <div class="form-group">
                      <div class="custom-control custom-checkbox small">
                        <input type="checkbox" class="custom-control-input" id="customCheck">
                        <label class="custom-control-label" for="customCheck">Remember Me</label>
                      </div>
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Login">
                    <hr>
                  </form>
                  <hr>
                  <div class="text-center">
                    <a class="small" href="forgot-password.html">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="register.html">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.js/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.js/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.js/sb-admin-2.min.js"></script>
  {% if loginFail == True %}
   <script> alert("Password is incorrect!") </script>
  {% endif %}

  {% if userExist == False %}
   <script> alert("User Id does not exist!") </script>
  {% endif %}
</body>

</html>

carpool/carpool/rider/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SR Admin 2 - Register</title>

  <!-- Custom fonts for this template-->
  <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">

   <style>
    .img-container {
      text-align: center;
      display: block;
      position: relative;
      top: 130px;
    }
  </style>

</head>

<body class="bg-gradient-primary">
  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block">
            <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.PNG' %}" alt="Carpool" align = "center"/>
            </span>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form action="{% url 'logPage:registerUser' %}" name = "registration"  onsubmit = "return validateForm()" method = "post" class="user">
                 {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user" name = "firstName" id="firstName" placeholder="First Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user" name ="lastName" id="lastName" placeholder="Last Name">
                  </div>
                </div>
                <div class="form-group">
                  <input type="text" class="form-control form-control-user"  name ="userId" id="userId" placeholder="User Id">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password" class="form-control form-control-user" name ="passWd" id="passWd" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password" class="form-control form-control-user"  name = "rpassWd" id="rpassWd" placeholder="Repeat Password">
                  </div>
                </div>
                  <input type="submit" class="btn btn-primary btn-user btn-block" value="OK">
              </form>
              <hr>
              <div class="text-center">
                <a class="small" href="forgot-password.html">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="login.html">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <script>
    function validateForm() {
    var val = document.forms["registration"]["firstName"].value;
    if (val == "") {
        alert("First Name can't be empty");
        return false;
      }
      var val = document.forms["registration"]["lastName"].value;
      if (val == "") {
        alert("Last Name can't be empty");
        return false;
      }
      var val = document.forms["registration"]["userId"].value;
      if (val.length < 6) {
        alert("userID should be at least 6 characters long");
        return false;
      }
      var val1 = document.forms["registration"]["passWd"].value;
      var val2 = document.forms["registration"]["rpassWd"].value;

      if(val1 != val2) {
        alert("Entered Passwords not matching");
        return false;
      }
  
      if(val1.length < 6) {
        alert("Password should be at least 6 characters long");
        return false;
      }
  } 
  </script>

  <!-- Bootstrap core JavaScript-->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <!-- Core plugin JavaScript-->
  <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for all pages-->
  <script src="js/sb-admin-2.min.js"></script>
  {% if userExist %}
   <script> alert("User Id already exists!") </script>
  {% endif %}

</body>

</html>

carpool/carpool/rider/templates/results.html
<!-- redirect page after ride acceptance -->
<!DOCTYPE html>
<html>
  <head>
    <title>Ajax</title>
  </head>
  <body>
    {% csrf_token %}}
      <h1>{ rideDetails.userId }</h1>
        
</body>
</html>

carpool/carpool/rider/templates/rideProcess.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SmartRide-Ride</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- <link href="{% static 'css/mapStyle.css' %}" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 130px;
      }
      .box{
        margin-top:2%;
        margin-left: auto;
        margin-right: auto;
        width:50%;
        height:20%;
        display: block;
        text-align: center;
        color: red;
      }
      .mapBox{
        margin-top:2%;
        margin-left:auto;
        margin-right: auto;
        width:60%;
        height:60%;
        display: block;
        border-radius: 6%;
      }


    </style>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map-canvas{
       min-width: 60vh;
       min-height: 60vh;
      }
    </style>
    <!-- <script src="{% static 'js/mapLocate.js' %}"></script> -->
</head>

<body class="bg-gradient-primary" style = "min-height: 100% ; min-width: 100% ;  background-image: url('/static/images/cab.gif');">

  
  <!-- <div id = "box-id" class = "box" style = "min-height: auto ; min-width: auto ;  background-image: url('/static/images/processing.gif');" ></div> -->
  <img src="{% static 'images/processing.gif' %}" style="margin-left: auto;margin-right: auto;display:block">
  <div class = "mapBox" id="map-canvas"></div>
  
  <script>
    var pickup = '{{paramDict.pickup}}',
    liveLat = '{{paramDict.latVal}}',
    liveLng = '{{paramDict.lngVal}}'

    function initMap() {

    console.log("initMap")
    console.log(pickup)
    console.log(liveLat)
    console.log(liveLng)
    var directionsService = new google.maps.DirectionsService();
    var directionsRenderer = new google.maps.DirectionsRenderer();
    var map = new google.maps.Map(document.getElementById('map-canvas'), {
      zoom: 7,
      center: {lat: 41.85 , lng: -87.65}
    });
    directionsRenderer.setMap(map);
    calculateAndDisplayRoute(directionsService, directionsRenderer);
    console.log("ended initMap")

    // document.getElementById('start').addEventListener('change', onChangeHandler);
    // document.getElementById('end').addEventListener('change', onChangeHandler);
  }
  
  function calculateAndDisplayRoute(directionsService, directionsRenderer ) {
    console.log("In calcandDisplay")
    // console.log(params)
    console.log(pickup)
    console.log(liveLat)
    console.log(liveLng)
    console.log("caclualte")

    directionsService.route(
    {
      origin: new google.maps.LatLng(liveLat , liveLng),
      destination: pickup,
      travelMode: 'DRIVING'
    },
    function(response, status) {
      if (status === 'OK') {
        directionsRenderer.setDirections(response);
      } else {
        window.alert('Directions request failed due to ' + status);
      }
    });
  }

  </script>
   <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG-rWicPLs2VaZF3WDK6yyl7tQqh-kUUc&callback=initMap">
  </script>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.js/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.js/jquery.easing.js/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.js/sb-admin-2.min.js' %}"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script type="text/javascript">
      console.log("hello ajax")


      function redirectPost(url, data) {
        var form = document.createElement('form');
        document.body.appendChild(form);
        form.method = 'post';
        form.action = url;
        for (var name in data) {
            var input = document.createElement('input');
            input.type = 'hidden';
            input.name = name;
            input.value = data[name];
            form.appendChild(input);
        }
        form.submit();
    }

      function wait(ms) { 
        const start = performance.now(); 
        while(performance.now() - start < ms); 
      }

      getMyJson();

      function getMyJson() {
        console.log("in ajax")
        var userID = '{{paramDict.userId}}'
        console.log(userID)
          $.ajax({
              type: "GET",
              url: '{% url "rider:statusUpdate"%}',
              data: {
                id : userID 
              },
              datatype: "json",
              success: function(result) {
              var json = result['userId'];
              if(result.success) { 
                  console.log("Ride Accepted!");
                  console.log(json);

                  //UNCOMMENT - to redirect
                  //redirectPost('{% url "rider:rideSuccessful"%}', { userId:result['userId']})
                  
              }else{
                  console.log("Response not yet met.");
                  //console.log(json);
                  wait(500);
                  console.log("calling again")
                  getMyJson();
              }
          },
          error: function() {
              console.log("There was an error.");
              // Want to repeat AJAX call also in case of error? 
              // Then just uncomment the following two lines:
              wait(1000);
              getMyJson();
          }
          });
      }
      
  </script>
</body>

</html>

carpool/carpool/rider/templates/riderHome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SmartRide-Ride Details</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- <link href="{% static 'css/mapStyle.css' %}" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 10%;
      }
    </style>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map-canvas{
        height: 60%;
        width: 60%;
      }
    </style>
    <script src="{% static 'js/mapSearch.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG-rWicPLs2VaZF3WDK6yyl7tQqh-kUUc&libraries=places&callback=initMap"></script>
</head>

<body class="bg-gradient-primary" style = "min-height: 100vh ; min-width: 100vh ;  background-image: url('/static/images/cab.gif');">

  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row" style="background-color: rgb(224, 240, 250);">
              <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.PNG' %}" alt="Carpool" align = "center"/>
                 </span>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">All set to go!!</h1>
                  </div>
                  <form action="{% url 'rider:rideInfo' %}" name = "rideInfo" method = "post" class= "rider">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name = "pickup" id="map-pickup" placeholder="Enter Pickup">
                      <br/>
                      <input type="text" class="form-control form-control-user" name = "destination" id="map-search" placeholder="Enter Destination">
                       <input type="hidden" id="lat" name="latVal">
                       <input type="hidden" id="lng" name="lngVal">
                       <input type="hidden" id = "userId" name = "userId" value = {{username}}>
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Submit">
                    <hr>
                  </form>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="map-canvas"></div>
      </div>

    </div>

  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.js/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.js/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.js/sb-admin-2.min.js' %}"></script>
  {% if loginFail == True %}
   <script> alert("Password is incorrect!") </script>
  {% endif %}

  {% if userExist == False %}
   <script> alert("User Id does not exist!") </script>
  {% endif %}

  <script type = "text/JavaScript">

  </script>
</body>

</html>
{#  <!-- Bootstrap core JavaScript-->#}
{#  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>#}
{#  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>#}
{##}
{#  <!-- Core plugin JavaScript-->#}
{#  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>#}
{##}
{#  <!-- Custom scripts for all pages-->#}
{#  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>#}
{#  {% if loginFail == True %}#}
{#   <script> alert("Password is incorrect!") </script>#}
{#  {% endif %}#}
{##}
{#  {% if userExist == False %}#}
{#   <script> alert("User Id does not exist!") </script>#}
{#  {% endif %}#}
{##}
{#  <script type = "text/JavaScript">#}
{##}
{#  </script>#}
{#</body>#}
{##}