carpool/carpool/carpool/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('logPage.urls')),
    path('rider/', include('rider.urls')),
    path('driver/', include('driver.urls'))
]

carpool/carpool/driver/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views
from rider.models import ride
app_name = 'driver'


urlpatterns = [
	path('' , views.driverHome , name = "driverHome"),
	path('driverInfo' , views.driverInfo , name = "driverInfo"),
	path('driveProcess' ,views.searchRider , name = "searchRider"),
	path('accept' ,views.acceptRider , name = "acceptRider" ),
	path('end', views.endRide , name ="endRide"),
	path('driverQuestions', views.driverQuestions, name="driverQuestions"),
	path('driverAnswer', views.driverAnswer, name="driverAnswer")
]

carpool/carpool/rider/urls.py
from django.urls import path 
from django.conf.urls import url
from . import views

app_name = 'rider'

# urlpatterns = [
# 	path('' , views.index , name = "index"),
# 	url(r'^(?P<album_id>[0-9]+)/$' , views.detail , name = "detail"),
# 	url(r'^(?P<album_id>[0-9]+)/favorite/$' , views.favorite , name = "favorite")
# ]

# urlpatterns = [
# 	path('' , views.IndexView.as_view() , name = "index"),
# 	url(r'^(?P<pk>[0-9]+)/$' , views.DetailView.as_view() , name = "detail"),
# 	url(r'^album/add/$', views.createAlbum.as_view() , name = "album-add")
# ]

urlpatterns = [
	path('' , views.index , name = "ride"),
	path('submit', views.rideInfo, name = "rideInfo"),
	path('processsing', views.statusUpdate, name = "statusUpdate"),
	path('success', views.rideSuccessful, name = "rideSuccessful"),
	path('riderQuestions', views.riderQuestions, name="riderQuestions"),
	path('riderAnswer', views.riderAnswer, name="riderAnswer")
	# path('rideRemove', views.endRide, name = "endRide"),
]

carpool/carpool/driver/models.py
from django.db import models

# Create your models here.

carpool/carpool/driver/views.py
from django.shortcuts import render
from django.http import HttpResponse ,Http404
from django.template import loader
from django.shortcuts import render , get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView , UpdateView , DeleteView
from django.http import JsonResponse
from rider.models import ride
from django.core import serializers
import re
import sqlite3

import numpy as np
import googlemaps 
import json
import time


def driverHome(request):
	print(request.user.username)	
	return render(request , "driverHome.html" , {'username' : request.user.username})

def driverInfo(request):
	print(request.user.username + " driveInfo")
	print(request.POST['destination'])
	return render(request , "driverProcess1.html" , {'username' : request.user.username , 'dest' : request.POST['destination']})

def searchRider(request):
	print("@@@@@@@@@@@@@@@@@@@@@@@@@*******************&&&&&&&&&&&&&&&&&&&&&&&&&&&**********************")
	print(request)
	driverId = request.GET['id']
	liveLat = request.GET['liveLat']
	liveLong = request.GET['liveLong']
	driver_dest = request.GET['destination']
	print(liveLat + "++++++" + liveLong);
	print(request.GET['destination'])
	print("*******************&&&&&&&&&&&&&&&&&&&&&&&&&&&**********************")

	if liveLat == "" or liveLong == "":
		return JsonResponse({'success': False})

	riderSet = ride.objects.select_for_update().filter(status = False , complete = False)
	rideList = []
	print(riderSet)
	print("####################----------------------------------------------------------------------------------------")
	gmaps = googlemaps.Client(key='AIzaSyCG-rWicPLs2VaZF3WDK6yyl7tQqh-kUUc')

	print("@@@@@@@@@@@@@@@@@@@@@----------------------------------------------------------------------------------------")
	driverRoutePoints = gmaps.directions((float(liveLat) ,float(liveLong)), driver_dest, mode="driving")

	time.sleep(10)

	driverRoutePoints = gmaps.directions((float(liveLat), float(liveLong)), driver_dest, mode="driving")
	# print(len(driverRoutePoints[0]))
	# print(type(driverRoutePoints[0]))
	# legs = driverRoutePoints[0].get("legs")
	# print("----------------------------------------------------------------------------------------")
	temp = []
	for leg in driverRoutePoints[0]['legs']:
		for step in leg['steps']:
			html_instructions = step['html_instructions']
			instr= step['distance']['text']
			instrtime=step['duration']['text']
			# print(step.keys())
			# print (html_instructions + " ||| " +instr+ " ||| " + instrtime + "!!!!!!!!!!!!!")
			# print(step.get("start_location"), " || ", step.get("end_location"))
			temp.append(step.get("start_location"))
			temp.append(step.get("end_location"))
	idx = np.round(np.linspace(0, len(temp) - 1, min(10, len(temp)))).astype(int)
	driverRoutePoints = []
	for x in idx:
		driverRoutePoints.append(temp[x])
	print(len(driverRoutePoints), "%%%%%%%%%%%%%%%%%")
	for r in riderSet:
		for point in driverRoutePoints:		
			# print(type(r))
			# print(r)
			# my_dist = gmaps.distance_matrix(point , r.pickUp)['rows'][0]['elements'][0]["distance"]["value"]
			print("point, pickup",point, r.pickUp )
			my_dist = gmaps.distance_matrix(point, r.pickUp)['rows'][0]['elements'][0]["distance"]["text"]
			my_dist = int(re.search(r'\d+', my_dist).group(0))

			print("my_dist", float(my_dist))
			my_dist = float(my_dist)/1000.0
			# my_dist_1 = gmaps.distance_matrix(driver_dest , r.destination)['rows'][0]['elements'][0]["distance"]["value"]
			# my_dist_1 = my_dist_1/1000.0
			expTime = gmaps.distance_matrix(r.pickUp , (liveLat, liveLong))['rows'][0]['elements'][0]["duration"]["text"]

			time.sleep(10)

			expTime = gmaps.distance_matrix(r.pickUp, (liveLat, liveLong))['rows'][0]['elements'][0]["duration"]["text"]
			# print(expTime , "-------------------------------------------")
			# cost = cost/1000.0
			# cost = cost*10
			# r.cost = cost
			# r.save()
			# print("the distance is " + str(my_dist))
			if my_dist < 60 :
				flag = False
				for point in driverRoutePoints:
					my_dist = gmaps.distance_matrix(point , r.destination)['rows'][0]['elements'][0]["distance"]["value"]

					time.sleep(10)

					my_dist = gmaps.distance_matrix(point, r.destination)['rows'][0]['elements'][0]["distance"]["value"]

					my_dist = my_dist/1000.0
					if my_dist < 60:
						flag = True
						break
				if flag == True:
					r.expectedTime = expTime
					data_dict = {'riderId':r.userId , 'pickUp': r.pickUp , 'destination' : r.destination}
					rideList.append(data_dict)
					r.save()
					break

	#rideList = json.dumps(rideList)
	return JsonResponse({'rideList': rideList})
	#algo rider search 

	#[{"model": "rider.ride", "pk": "lodhuji", "fields": {"pickUp": "Bhopal Railway Station, Bajariya, Navbahar Colony, Bhopal, Madhya Pradesh, India", "destination": "New Delhi, Delhi, India", "complete": false, "status": false, "cost": 0}}]

def acceptRider(request):
	print(request)
	print("***************************")
	idList = request.GET['id']
	ind = idList.find("&&&----&&&")
	driverId = idList[:ind]
	riderId = idList[ind+10: ]
	print(driverId)
	print(riderId)
	success =  ride.acceptRide(riderId , driverId)
	acceptedSet = ride.objects.select_for_update().filter(status = True , driverId = driverId , complete = False)
	acceptList = []

	for r in acceptedSet:
		print(r)
		data_dict = {'riderId':r.userId , 'pickUp': r.pickUp , 'destination' : r.destination}
		acceptList.append(data_dict)
	
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	print(acceptList)
	print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")
	return JsonResponse({'success' : success , 'acceptList' : acceptList})


#<WSGIRequest: GET '/driver/accept?riderId=lodhuji&driverId=User01'>
#<WSGIRequest: GET '/driver/driveProcess?id=User01&liveLat=19.7514798&liveLong=75.7138884&destination=New%20Delhi%20Railway%20Station%2C%20Kamla%20Market%2C%20Ajmeri%20Gate%2C%20New%20Delhi%2C%20Delhi%2C%20India'>

def endRide(request):
	idList = request.GET['id']
	ind = idList.find("&&&----&&&")
	driverId = idList[:ind]
	riderId = idList[ind+10: ]
	print(driverId)
	print(riderId)
	r = get_object_or_404(ride, pk=riderId)
	r.complete = True
	r.save()

	acceptedSet = ride.objects.select_for_update().filter(status = True , driverId = driverId , complete = False)
	acceptList = []

	for r in acceptedSet:
		print(r)
		data_dict = {'riderId':r.userId , 'pickUp': r.pickUp , 'destination' : r.destination}
		acceptList.append(data_dict)

	print(acceptList)
	print("------------------------------------------------- "+str(r.cost) + " ----------------------------------------------")
	return JsonResponse({'success' : True , 'acceptList' : acceptList, 'cost' : r.cost})

def driverQuestions(request):
    print(request.user.username)
    return render(request, "driverSideQuestions.html", {'username': request.user.username})


def driverAnswer(request):
    if request.method == "POST":
        userid = request.user.username
        driverid = userid
        talkative = request.POST.get('talkative')
        timedriving = request.POST.get('timedriving')
        music = request.POST.get('music')
        male = request.POST.get('male')
        female = request.POST.get('female')
        workstudent = request.POST.get('workstudent')
        con = sqlite3.connect("db.sqlite3")
        cur = con.cursor()
        values = (userid, driverid, talkative, timedriving, music, male, female, workstudent)
        cur.execute("insert into driverquestion values (?, ?, ?, ?, ?, ?, ?, ?)", values)
        con.commit()
        return render(request, "driverHome.html", {'username': request.user.username})
	

carpool/carpool/driver/templates/driverHome.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SmartRide - Details</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- <link href="{% static 'css/mapStyle.css' %}" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 10%;
      }
    </style>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map-canvas{
        height: 60%;
        width: 60%;
      }
    </style>
    <script src="{% static 'js/mapSearch.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG-rWicPLs2VaZF3WDK6yyl7tQqh-kUUc &libraries=places&callback=initMap"></script>
</head>

<body class="bg-gradient-primary" style = "min-height: 100vh ; min-width: 100vh ;  background-image: url('/static/images/cab.gif');">

  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row" style="background-color: rgb(224, 240, 250);">
              <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.PNG' %}" alt="Carpool" align = "center"/>
                 </span>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">All set to go!!</h1>
                  </div>
                  <form action="{% url 'driver:driverInfo' %}" name = "driverInfo" method = "post" class= "driver">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="text" class="form-control form-control-user" name = "destination" id="map-search" placeholder="Enter Destination">
                       <input type="hidden" id="lat" name="latVal">
                       <input type="hidden" id="lng" name="lngVal">
                       <input type="hidden" id = "userId" name = "userId" value = {{username}}>
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Submit">
                    <hr>
                  </form>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="map-canvas"></div>
      </div>

    </div>

  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  {% if loginFail == True %}
   <script> alert("Password is incorrect!") </script>
  {% endif %}

  {% if userExist == False %}
   <script> alert("User Id does not exist!") </script>
  {% endif %}
</body>

</html>

carpool/carpool/driver/templates/driverProcess.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SR Admin 2 - Login</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <!-- <link href="{% static 'css/mapStyle.css' %}" rel="stylesheet" type="text/css"> -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

   <style>
      .img-container {
        text-align: center;
        display: block;
        position: relative;
        top: 10%;
      }
    </style>
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map-canvas{
        height: 60%;
        width: 60%;
      }
    </style>
    <script src="{% static 'js/getLocate.js' %}"></script>
    <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG-rWicPLs2VaZF3WDK6yyl7tQqh-kUUc &libraries=places&callback=initMap"></script>
</head>

<body class="bg-gradient-primary" style = "min-height: 100vh ; min-width: 100vh ;  background-image: url('/static/images/cab.gif');">

  <div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row" style="background-color: rgb(224, 240, 250);">
              <div class="col-lg-6 d-none d-lg-block"> 
                 <span class="img-container"> <!-- Inline parent element -->
                  <img src="{% static 'images/carpool1.jpeg' %}" alt="Carpool" align = "center"/>
                 </span>
              </div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">All set to go!!</h1>
                  </div>
                  <form action="{% url 'driver:driverInfo' %}" name = "driverInfo" method = "post" class= "driver">
                    {% csrf_token %}
                    <div class="form-group">
                      <input type="hidden" class="form-control form-control-user" name = "destination" id="map-search" value = {{dest}}>
                       <input type="hidden" id="lat" name="latVal">
                       <input type="hidden" id="lng" name="lngVal">
                       <input type="hidden" id = "userId" name = "userId" value = {{username}}>
                    </div>
                    <input type="submit" class="btn btn-primary btn-user btn-block" value="Submit">
                    <hr>
                  </form>
                  <hr>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div id="map-canvas"></div>
      </div>

    </div>

  </div>
  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
  {% if loginFail == True %}
   <script> alert("Password is incorrect!") </script>
  {% endif %}

  {% if userExist == False %}
   <script> alert("User Id does not exist!") </script>
  {% endif %}
  <script type="text/javascript">
      console.log("hello ajax")

      function redirectPost(url, data) {
        var form = document.createElement('form');
        document.body.appendChild(form);
        form.method = 'post';
        form.action = url;
        for (var name in data) {
            var input = document.createElement('input');
            input.type = 'hidden';
            input.name = name;
            input.value = data[name];
            form.appendChild(input);
        }
        form.submit();
    }

      function wait(ms) { 
        const start = performance.now(); 
        while(performance.now() - start < ms); 
      }

      //getRider();
      var destPoint = '{{dest}}'
      var userID = '{{username}}'

      function getRider(callback) {
        console.log("in ajax")
        //initMap()
        console.log("after initMap")
        console.log(document.getElementById('map-search').value)

        $.ajax({
          type: "GET",
          url: '{% url "driver:searchRider"%}',
          data: {
            id : userID,
            liveLat : document.getElementById('lat').value,
            liveLong : document.getElementById('lng').value,
            destination : destPoint
          },
          datatype: "json",
          success: function(result) {
          console.log(result.rideList) //Here is the list of potential rides after algo: Iterate over this and do dynamic render
          console.log("ride Accepted")  //of Cards using JS. Aslo check for empty or something

          },
          error: function() {
              console.log("There was an error.");
              // Want to repeat AJAX call also in case of error? 
              // Then just uncomment the following two lines:
          }
      });
    
    }

      $(document).ready(function(){
             console.log("Calling getRider once more")
             setInterval(getRider,120000);
      });

      // window.addEventListener('load',function(){
      //   getRider();
      // },false);

  </script>
</body>

</html>





<!-- function getRider(callback) {
        console.log("in ajax")
        //initMap()
        console.log("after initMap")
        console.log(document.getElementById('map-search').value)
  
          $.ajax({
              type: "GET",
              url: '{% url "driver:searchRider"%}',
              data: {
                id : userID,
                liveLat : document.getElementById('lat').value,
                liveLong : document.getElementById('lng').value,
                destination : destPoint
              },
              datatype: "json",
              success: function(result) {
              var json = result['userId'];

              if(result.success) { 
                  console.log("Ride Accepted!------------------------------");
                  console.log(result.rideLi)
                  //UNCOMMENT - to redirect
                  //redirectPost('{% url "rider:rideSuccessful"%}', { userId:result['userId']})
              }else{
                  console.log("Response not yet met.");
                  //console.log(json);
                  wait(500);
                  console.log("calling again")
                  getRider();
              }
          },
          error: function() {
              console.log("There was an error.");
              // Want to repeat AJAX call also in case of error? 
              // Then just uncomment the following two lines:
              wait(1000);
              getRider();
          }
          });
      }

      window.addEventListener('load',function(){
        getRider();
      },false);
 -->

carpool/carpool/driver/templates/driverSideQuestions.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
    <title>SmartRide - Questions for Driver</title>
 <!-- Custom fonts for this template-->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <!-- <link href="{% static 'css/mapStyle.css' %}" rel="stylesheet" type="text/css"> -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">

     <style>
        .img-container {
          text-align: center;
          display: block;
          position: relative;
          top: 10%;
        }
        .mapBox{
          margin-top:10%;
          margin-left:auto;
          margin-right: auto;
          width:60%;
          height:60%;
          display: block;
          border-radius: 6%;
        }
      </style>
      <style>
        /* Always set the map height explicitly to define the size of the div
         * element that contains the map. */
        #map-canvas{
          height: 80%;
          width: 80%;
        }
      </style>
      <!-- <script src="{% static 'js/mapSearch.js' %}"></script> -->
      <script src="{% static 'js/getLocate.js' %}"></script>
      <script src="{% static 'js/utility.js' %}"></script>
      <script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCG-rWicPLs2VaZF3WDK6yyl7tQqh-kUUc &libraries=places&callback=initMap"></script>
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
       <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

</head>
<body>
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
      <div class="col-xl-10 col-lg-12 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row" style="background-color: rgb(224, 240, 250);">
              <div class="col-lg-12">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Who can be your unknown rider in the car</h1>
                   </div>
                     <form action="{% url 'driver:driverAnswer' %}" name = "driverAnswer" method = "post" class= "driver">
                    {% csrf_token %}
                         {{ form.as_p }}
                    <div class="form-group">
                       <label>1) Do you prefer talkative rider?</label><br>
                      <input type="radio" id="yes" name="talkative" value="Yes">
                      <label for="yes"> Yes</label><br>

                      <input type="radio" id="no" name="talkative" value="No">
                      <label for="no">No</label><br>

                      <input type="radio" id="any" name="talkative" value="Any">
                      <label for="any">Any</label><br><br>

                      <label>2) Do you prefer on time driving?</label><br>
                      <input type="radio" id="yes" name="timedriving" value="Yes">
                      <label for="yes"> Yes</label><br>

                      <input type="radio" id="no" name="timedriving" value="No">
                      <label for="no">No</label><br>

                      <input type="radio" id="any" name="timedriving" value="Any">
                      <label for="any">Any</label><br><br>

                     <label>3) Do you like music while travelling?</label><br>
                      <input type="radio" id="yes" name="music" value="Yes">
                      <label for="yes"> Yes</label><br>

                      <input type="radio" id="no" name="music" value="No">
                      <label for="no">No</label><br>

                      <input type="radio" id="any" name="music" value="Any">
                      <label for="any">Any</label><br><br>

                      <label>4) Do you prefer only male?</label><br>
                      <input type="radio" id="yes" name="male" value="Yes">
                      <label for="yes"> Yes</label><br>

                      <input type="radio" id="no" name="male" value="No">
                      <label for="no">No</label><br>

                      <input type="radio" id="any" name="male" value="Any">
                      <label for="any">Any</label><br><br>

                      <label>5) Do you prefer only female?</label><br>
                      <input type="radio" id="yes" name="female" value="Yes">
                      <label for="yes"> Yes</label><br>

                      <input type="radio" id="no" name="female" value="No">
                      <label for="no">No</label><br>

                      <input type="radio" id="any" name="female" value="Any">
                      <label for="any">Any</label><br><br>

                      <label>6) Do you prefer working person, or Students as a rider would be fine?</label><br>
                      <input type="radio" id="yes" name="workstudent" value="Yes">
                      <label for="yes"> Yes</label><br>

                      <input type="radio" id="no" name="workstudent" value="No">
                      <label for="no">No</label><br>

                      <input type="radio" id="any" name="workstudent" value="Any">
                      <label for="any">Any</label><br><br>

                       <input type="submit" class="btn btn-primary btn-user btn-block" value="Submit"><br>

                        <b style="margin-left: 46%;">OR</b><br><br>

                        <a href="{% url 'driver:driverHome' %}" class="btn btn-primary btn-user btn-block">
                            Skip
                        </a>
                        {% if message %}
                            {% for message in message %}
                                {{ message }}
                            {% endfor %}
                        {% endif %}
                       <input type="hidden" id="lat" name="latVal">
                       <input type="hidden" id="lng" name="lngVal">
                       <input type="hidden" id = "userId" name = "userId" value = {{username}}>
                    </div>
                         <hr>
                  </form>
                  </div>
              </div>
            </div>
          </div>
        </div>
        <div id="map-canvas"></div>
      </div>
    </div>
  </div>

<!-- Bootstrap core JavaScript-->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

</body>
</html>